(async()=>{
const api=window.GnomAPI,$=q=>document.querySelector(q),esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const s={products:[],settings:null,inquiries:[],views:[],email:''};
const msg=(t,b=false)=>{const e=$('#admin-message');e.textContent=t;e.className=b?'error':'notice';setTimeout(()=>e.classList.add('hidden'),3500)};
async function guard(){try{const u=await api.getUser();const p=await api.select('profiles',`select=role&id=eq.${encodeURIComponent(u.id)}&limit=1`);if(!p?.[0]||p[0].role!=='admin')throw 0;s.email=u.email||'';$('#owner-email').textContent=s.email;return true}catch{api.clearTokens();location.href='../login/';return false}}
async function load(){const [p,st,i,v]=await Promise.all([api.select('products','select=*&order=sort_order.asc'),api.select('site_settings','select=*&id=eq.1&limit=1'),api.select('inquiries','select=*&order=created_at.desc'),api.select('page_views','select=*&order=created_at.asc')]);s.products=p||[];s.settings=st?.[0];s.inquiries=i||[];s.views=v||[];render()}
function render(){stats();products();inquiries();settings();visits()}
function stats(){const active=s.products.filter(x=>x.active).length,total=s.products.reduce((a,x)=>a+x.stock,0),low=s.products.filter(x=>x.stock>0&&x.stock<=3).length,out=s.products.filter(x=>x.stock===0).length;$('#stats').innerHTML=[['Товаров на сайте',active],['Всего вещей',total],['Мало осталось',low],['Нет в наличии',out]].map(([l,n])=>`<article class="stat"><span>${l}</span><strong>${n}</strong></article>`).join('');$('#latest-inquiries').innerHTML=s.inquiries.slice(0,5).map(x=>`<div class="table-row"><span><b>${esc(x.customer_name)}</b><br><small>${esc(x.product_name||'Без товара')}</small></span><b>${esc(x.status)}</b></div>`).join('')||'<p>Заявок пока нет.</p>';$('#low-stock').innerHTML=s.products.filter(x=>x.stock<=3).map(x=>`<div class="table-row"><span>${esc(x.name)}</span><b>${x.stock} шт.</b></div>`).join('')||'<p>Низких остатков нет.</p>'}
function visits(){const now=new Date(),today=now.toISOString().slice(0,10),d=v=>new Date(v.created_at).toISOString().slice(0,10),since=n=>{const x=new Date(now);x.setDate(now.getDate()-n+1);return s.views.filter(v=>new Date(v.created_at)>=x).length};$('#visit-stats').innerHTML=[['Сегодня',s.views.filter(v=>d(v)===today).length],['За 7 дней',since(7)],['За 30 дней',since(30)],['Всего',s.views.length]].map(([l,n])=>`<article class="stat"><span>${l}</span><strong>${n}</strong></article>`).join('');const m={};for(let k=13;k>=0;k--){const x=new Date(now);x.setDate(now.getDate()-k);m[x.toISOString().slice(0,10)]=0}s.views.forEach(v=>{const x=d(v);if(x in m)m[x]++});const max=Math.max(1,...Object.values(m));$('#visit-bars').innerHTML=Object.entries(m).map(([x,n])=>`<div class="visit-bar" title="${x}: ${n}" style="height:${Math.max(4,n/max*100)}%"><span>${n}</span></div>`).join('');const ru=s.views.filter(v=>v.language==='ru').length,en=s.views.filter(v=>v.language==='en').length;$('#view-pages').innerHTML=`<div class="table-row"><span>🇷🇺 Русская версия <small>/</small></span><b>${ru}</b></div><div class="table-row"><span>🌍 English version <small>/en</small></span><b>${en}</b></div>`}
function products(){const r=$('#product-list');r.innerHTML=s.products.map((p,i)=>`<article class="product-editor"><div class="product-title"><div class="product-icon">${esc(p.icon)}</div><div><b>${esc(p.name)}</b><small>${esc(p.category)} · ${p.stock} шт.</small></div></div><div class="form-grid"><label>Название<input class="field pf" data-i="${i}" data-k="name" value="${esc(p.name)}"></label><label>Категория<input class="field pf" data-i="${i}" data-k="category" value="${esc(p.category)}"></label><label>Цена, ₽<input class="field pf" data-i="${i}" data-k="price_rub" type="number" min="0" value="${p.price_rub}"></label><label>Остаток<input class="field pf" data-i="${i}" data-k="stock" type="number" min="0" value="${p.stock}"></label><label>Размеры<input class="field pf" data-i="${i}" data-k="sizes" value="${esc(p.sizes)}"></label><label>Эмодзи<input class="field pf" data-i="${i}" data-k="icon" value="${esc(p.icon)}"></label><label>Ярлык<input class="field pf" data-i="${i}" data-k="badge" value="${esc(p.badge)}"></label><label>Порядок<input class="field pf" data-i="${i}" data-k="sort_order" type="number" value="${p.sort_order}"></label><label>Цвет<select class="field pf" data-i="${i}" data-k="color">${['pink','orange','yellow','mint'].map(c=>`<option ${p.color===c?'selected':''}>${c}</option>`).join('')}</select></label><label>На сайте<select class="field pf" data-i="${i}" data-k="active"><option value="true" ${p.active?'selected':''}>Да</option><option value="false" ${!p.active?'selected':''}>Нет</option></select></label></div><label class="full-label">Описание<textarea class="field pf" data-i="${i}" data-k="description" rows="2">${esc(p.description)}</textarea></label><div class="editor-actions"><button class="btn orange psave" data-i="${i}">Сохранить</button><button class="btn danger pdel" data-i="${i}">Удалить</button></div></article>`).join('');r.querySelectorAll('.pf').forEach(e=>e.addEventListener('input',()=>{const i=+e.dataset.i,k=e.dataset.k;let v=e.value;if(['price_rub','stock','sort_order'].includes(k))v=Number(v);if(k==='active')v=v==='true';s.products[i][k]=v}));r.querySelectorAll('.psave').forEach(b=>b.onclick=()=>saveProduct(+b.dataset.i));r.querySelectorAll('.pdel').forEach(b=>b.onclick=()=>delProduct(+b.dataset.i))}
async function saveProduct(i){const p=s.products[i],body={name:p.name,category:p.category,price_rub:p.price_rub,sizes:p.sizes,stock:p.stock,icon:p.icon,color:p.color,badge:p.badge,description:p.description,active:p.active,sort_order:p.sort_order,updated_at:new Date().toISOString()};try{await api.update('products',`id=eq.${p.id}`,body);msg('Товар сохранён');await load()}catch(e){msg(e.message,true)}}
async function delProduct(i){const p=s.products[i];if(!confirm(`Удалить «${p.name}»?`))return;try{await api.remove('products',`id=eq.${p.id}`);msg('Товар удалён');await load()}catch(e){msg(e.message,true)}}
async function addProduct(){try{await api.insert('products',{name:'Новый товар',category:'Костюмы',price_rub:0,sizes:'',stock:0,icon:'🧸',color:'pink',badge:'',description:'',active:false,sort_order:0});msg('Товар добавлен');await load()}catch(e){msg(e.message,true)}}
function inquiries(){const r=$('#inquiry-list');r.innerHTML=s.inquiries.map(x=>`<article class="inquiry"><div><small>${new Date(x.created_at).toLocaleString('ru-RU')}</small><h3>${esc(x.customer_name)}</h3><a href="tel:${esc(x.phone)}">${esc(x.phone)}</a>${x.product_name?`<p><b>Товар:</b> ${esc(x.product_name)}</p>`:''}</div><div class="status-buttons">${[['new','Новая'],['contacted','Связались'],['done','Готово']].map(([v,l])=>`<button class="btn ${x.status===v?'pink':'outline'} ist" data-id="${x.id}" data-v="${v}">${l}</button>`).join('')}</div></article>`).join('')||'<div class="box">Заявок пока нет.</div>';r.querySelectorAll('.ist').forEach(b=>b.onclick=async()=>{try{await api.update('inquiries',`id=eq.${b.dataset.id}`,{status:b.dataset.v});await load()}catch(e){msg(e.message,true)}})}
function settings(){const st=s.settings;if(!st)return;const f=[['store_name','Название'],['phone','Телефон'],['address','Адрес'],['hours','Режим работы'],['contact_link','Ссылка Telegram / VK / WhatsApp'],['hero_title','Главный заголовок'],['hero_text','Текст на главной'],['promo_title','Заголовок акции'],['promo_text','Описание акции']];const r=$('#settings-form');r.innerHTML=f.map(([k,l])=>`<label class="${['contact_link','hero_title','hero_text','promo_title','promo_text'].includes(k)?'wide':''}">${l}${['hero_text','promo_text'].includes(k)?`<textarea class="field sf" data-k="${k}" rows="3">${esc(st[k]||'')}</textarea>`:`<input class="field sf" data-k="${k}" value="${esc(st[k]||'')}">`}</label>`).join('');r.querySelectorAll('.sf').forEach(e=>e.oninput=()=>s.settings[e.dataset.k]=e.value)}
async function saveSettings(){const x=s.settings,b={store_name:x.store_name,hero_title:x.hero_title,hero_text:x.hero_text,address:x.address,phone:x.phone,hours:x.hours,contact_link:x.contact_link,promo_title:x.promo_title,promo_text:x.promo_text,updated_at:new Date().toISOString()};try{await api.update('site_settings','id=eq.1',b);msg('Настройки сохранены');await load()}catch(e){msg(e.message,true)}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#panel-'+b.dataset.tab).classList.add('active')});$('#add-product').onclick=addProduct;$('#save-settings').onclick=saveSettings;$('#logout').onclick=async()=>{await api.logout();location.href='../login/'};if(await guard())load().catch(e=>msg(e.message||'Ошибка загрузки',true));
})();
